version: "3"

services:
  
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  django_app:
    build: .
    #image: django:1.0
    volumes:
      - ./config:/opt/portfolio/config
      - ./portfolio:/opt/portfolio
    depends_on:
      - db_postgres
    restart: always
    
  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/portfolio/static
    depends_on:
      - django_app
    restart: always

volumes:
  #.:
  postgres_data:
  static:

