version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  django_app:
    #build: .
    image: django:1.0
    volumes:
      #- static:/code/static
      - ./portfolio:/opt/portfolio
    depends_on:
      - db_postgres
    restart: always
    
  nginx:
    image: nginx:1.13
    ports:
      - 8008:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app
    restart: always

volumes:
  #.:
  postgres_data:
  static:


# services:
#   web:
#     image: django:1.0
#     volumes: 
#       - ./portfolio:/opt/portfolio
#     ports: 
#       - 8000:8000